# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- asure-branch

pool:
  vmImage: ubuntu-latest


stages:
  - stage: 'sample code'
    displayName: 'sample stage'
    jobs:
      - job: 'sampleCode'
        displayName: 'Running unit tests'
        steps:
          - script: echo 'Running simple Nodejs api'

          - task: NodeTool@0
            inputs:
              versionSpec: '6.x'